# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost
  port: 3306
  encoding: utf8

development:
  <<: *default
  database: ****
  username: ****
  password: ****   

production:
  <<: *default
  database: ****
  username: ****
  password: ****
